# .bashrc for sandbox users
# Generated by the example profile.

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Sandbox on-enter hook (set up by apply_profile.sh)
if [ -f ~/.sandbox-enter ]; then
    source ~/.sandbox-enter
fi

# Basic prompt
PS1='\[\e[32m\]\u@\h\[\e[0m\]:\[\e[34m\]\w\[\e[0m\]\$ '

# Aliases
alias ll='ls -la'
alias la='ls -A'
